/*
 * export-config.js —— 从 00-config.js 生成 C# 的 Config.g.cs
 *
 * **硬规矩没变：`00-config.js` 仍然是所有数字的唯一出处。**
 * C# 那边的配置是【生成】的，不是手抄的 —— 手抄意味着两份数字，
 * 而两份数字迟早会漂，且没有任何东西会报错。
 *
 * 跑法：node campus/unity/tools/export-config.js
 */
const path = require('path');
const fs = require('fs');
const SRC = path.join(__dirname, '..', '..', 'web-m0', 'src');
require(path.join(SRC, '03-math.js'));
require(path.join(SRC, '00-config.js'));
require(path.join(SRC, '21-items.js'));
const C = globalThis.Campus;

const pas = (s) => String(s).replace(/[^A-Za-z0-9_]/g, '_').replace(/^(\d)/, '_$1')
  .replace(/^[a-z]/, (m) => m.toUpperCase());

function isScalar(v) { return v === null || ['number', 'string', 'boolean'].includes(typeof v); }
function csLit(v) {
  if (v === null) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') {
    // JS 的 Infinity / NaN 在 C# 里是别的写法，直接 String(v) 会生成编译不过的代码
    if (!isFinite(v)) return v > 0 ? 'double.PositiveInfinity' : (v < 0 ? 'double.NegativeInfinity' : 'double.NaN');
    return Number.isInteger(v) ? v + '.0' : String(v);
  }
  return JSON.stringify(v);
}

/* 每个值都同时生成两样东西：
     ① 一个强类型的 `const` / `static readonly` —— 写代码时有补全、有编译检查
     ② 一个 `Raw` 字典 —— 测试和调试要按名字遍历（「所有响度都必须 ≥0」这类断言）
   只有 ① 的话没法写通用断言，只有 ② 的话业务代码就变成了字符串魔法。 */
const lines = [];
const push = (n, s) => lines.push('  '.repeat(n) + s);

function emitObject(name, obj, depth, path) {
  push(depth, `public static class ${name} {`);
  const scalars = [], nested = [], arrays = [];
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (typeof v === 'function') continue;
    if (isScalar(v)) scalars.push([k, v]);
    else if (Array.isArray(v)) arrays.push([k, v]);
    else nested.push([k, v]);
  }
  for (const [k, v] of scalars) {
    const t = v === null ? 'double?' : typeof v === 'boolean' ? 'bool' : typeof v === 'number' ? 'double' : 'string';
    // `const` 只能用于编译期常量：字符串可以，但 `double?` 和非有限数不行
    const kw = (typeof v === 'string' || v === null || (typeof v === 'number' && !isFinite(v)))
      ? 'static readonly' : 'const';
    push(depth + 1, `public ${kw} ${t} ${pas(k)} = ${csLit(v)};`);
  }
  for (const [k, v] of arrays) {
    /* 只有**元素类型一致**的标量数组才生成强类型数组。
       混合数组（`skill: ['cooking', 2]`）在 C# 里没有对应的类型，
       硬生成会得到 `string[] { "cooking", 2.0 }` 这种编译不过的东西。 */
    const allNum = v.length > 0 && v.every(x => typeof x === 'number');
    const allStr = v.length > 0 && v.every(x => typeof x === 'string');
    if (allNum || allStr) {
      const t = allNum ? 'double' : 'string';
      push(depth + 1, `public static readonly ${t}[] ${pas(k)} = { ${v.map(csLit).join(', ')} };`);
    } else {
      // 非标量数组（配方表、角色表…）作为 JSON 常量带过去，运行时按需解析
      push(depth + 1, `public const string ${pas(k)}Json = ${JSON.stringify(JSON.stringify(v))};`);
    }
  }
  // 同名的字典视图：值全是数的才生成（响度表、衰减表都属于这一类）
  if (scalars.length && scalars.every(([, v]) => typeof v === 'number')) {
    /* 字典视图叫 `Values` 不叫 `Raw` —— `food` 底下本来就有一个 `raw`（生食表），
       两者会撞名。生成器撞名是最难查的一类错误，因为它只在特定数据下出现。 */
    push(depth + 1, `public static readonly System.Collections.Generic.Dictionary<string, double> Values = new System.Collections.Generic.Dictionary<string, double> {`);
    for (const [k, v] of scalars) push(depth + 2, `{ ${JSON.stringify(k)}, ${csLit(v)} },`);
    push(depth + 1, '};');
  }
  for (const [k, v] of nested) emitObject(pas(k), v, depth + 1, path + '.' + k);
  push(depth, '}');
}

push(0, '// <auto-generated>');
push(0, '// 由 campus/unity/tools/export-config.js 从 campus/web-m0/src/00-config.js 生成。');
push(0, '// **不要手改这个文件** —— 改 00-config.js 然后重新生成。');
/* **不写生成时间。**
   写了的话每次重新生成都会改这一行，于是 `git diff` 永远是脏的，
   「配置真的变了」和「有人跑了一遍生成器」就再也分不开了。
   什么时候生成的，git 比这行注释清楚。 */
push(0, '// </auto-generated>');
push(0, 'namespace Campus {');
push(1, 'public static partial class Config {');
for (const key of Object.keys(C.Config)) {
  const v = C.Config[key];
  if (typeof v === 'function') continue;
  if (Array.isArray(v)) {
    push(2, `public const string ${pas(key)}Json = ${JSON.stringify(JSON.stringify(v))};`);
  } else if (isScalar(v)) {
    push(2, `public const double ${pas(key)} = ${csLit(v)};`);
  } else {
    emitObject(pas(key), v, 2, key);
  }
}
push(2, `public const string ItemsJson = ${JSON.stringify(JSON.stringify(C.ITEMS))};`);
/* 整份配置的 JSON 也带过去。
   生成的静态类给的是**强类型常量**（写业务代码时有补全和编译检查），
   但有些表的形状用 C# 的嵌套静态类表达不了 ——
   比如 `portalAttenuation[类型][状态]` 的值可以是 null（「这个类型没有这个状态」）。
   那几张表由手写的 `Config.Tables.cs` 从这份 JSON 建出来，类型正确、来源仍然唯一。 */
push(2, `public const string AllJson = ${JSON.stringify(JSON.stringify(C.Config))};`);
push(1, '}');
push(0, '}');

const out = path.join(__dirname, '..', 'Campus.Core', 'Config.g.cs');
fs.writeFileSync(out, lines.join('\n') + '\n');
console.log('已生成 ' + path.relative(process.cwd(), out) + '  ' +
            (fs.statSync(out).size / 1024).toFixed(0) + ' KB');
